# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AwesomeNotes' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AwesomeNotes
  pod 'Alamofire', '~> 3.0'
	
  target 'AwesomeNotesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AwesomeNotesUITests' do
    # Pods for testing
  end

end
